# Generated by Django 4.0.4 on 2022-06-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birth', models.CharField(max_length=30)),
                ('death', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(null=True)),
                ('nationality', models.CharField(max_length=30)),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField()),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.curator')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('dateMade', models.CharField(max_length=30)),
                ('dateAcquired', models.CharField(max_length=30)),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
                ('dimensions', models.CharField(max_length=60)),
                ('framed', models.BooleanField(default=False)),
                ('signature', models.BooleanField(default=False)),
                ('image', models.URLField()),
                ('artist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='app_api.artist')),
                ('classification', models.ManyToManyField(default=None, related_name='classification', to='app_api.classification')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.curator')),
                ('genre', models.ManyToManyField(default=None, related_name='genres', to='app_api.genre')),
                ('medium', models.ManyToManyField(default=None, related_name='mediums', to='app_api.medium')),
                ('style', models.ManyToManyField(default=None, related_name='styles', to='app_api.style')),
            ],
        ),
    ]
