# Generated by Django 4.0.4 on 2022-06-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birth', models.CharField(max_length=30)),
                ('death', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(null=True)),
                ('nationality', models.CharField(max_length=30)),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField()),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.curator')),
            ],
        ),
    ]
