# Generated by Django 4.0.4 on 2022-06-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('dateMade', models.CharField(max_length=30)),
                ('dateAcquired', models.CharField(max_length=30)),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
                ('dimensions', models.CharField(max_length=60)),
                ('framed', models.BooleanField(default=False)),
                ('signature', models.BooleanField(default=False)),
                ('image', models.URLField()),
                ('artistId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='app_api.artist')),
                ('classificationId', models.ManyToManyField(default=None, related_name='classification', to='app_api.classification')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.curator')),
                ('genreId', models.ManyToManyField(default=None, related_name='genres', to='app_api.genre')),
                ('mediumId', models.ManyToManyField(default=None, related_name='mediums', to='app_api.medium')),
                ('styleId', models.ManyToManyField(default=None, related_name='styles', to='app_api.style')),
            ],
        ),
    ]
