from .auth_view import login_user
from .auth_view import register_user
from .artist_view import ArtistView
from .user_view import UserView
from .classification_view import ClassificationView
from .genre_view import GenreView
from .style_view import StyleView
from .medium_view import MediumView
from .art_view import ArtView
